# Background
Freshwater streams are very sensitive to disturbances. Disturbances, such as hurricanes, can significantly alter the stream water chemistry for years. In 1989, Hurricane Hugo struck Puerto Rico, leaving a trail of damage along its path. In a study called *Effects of hurricane disturbance on stream water concentrations and fluxes in eight tropical forest watersheds of the Luquillo Experimental Forest, Puerto Rico* by [Schaefer et al.](/paper/original_paper.pdf), the effects of Hugo on local streamwater chemistry are investigated for 2.5-11 years following the hurricane. In this study, scientists cleaned years of data to produce a smoothed time series of 5 different ions in four different locations. The motivation for the following analysis is to reproduce figure #3 from this study.

# Data
## Data and Locations: 
The four locations that we are looking at are PRM, BQ1, BQ2, and BQ3. These locations correspond to the testing sites Quebradas 1, 2, 3 (BQ1, BQ2, NQ3), and Puente Roto Mameyes (PRM). In the raw data, they have different names, so we will rename them to match the original paper. All of the data cleaning is done in an accessory script called 1_clean_data.R. There are five ions that we are looking at: Potassium (k), Magnesium (mg), Calcium (ca), Nitrate (no3), and Ammonium (nh4).


# Methods
## Filter data with moving average function
The 1_clean_data.R script cleans all our data by applying a 9 week moving average to each of the ions to create an average concentration. 

### Function Definition
The function moving_average(), found in /R, is the primary function for cleaning the data. It creates 9 week windows for the whole span of the dataset, and takes the average concentration value for each ion at each location in that 9-week window. It then puts all of the smoothed data into a new dataframe with the window start dates, individual ion concentrations, and 3 letter location marker.

### Apply function to the datset
The 1_clean_data.R script applies the moving average function to each dataset and then combines them into one large smoothed dataset. Then, for logistical purposes, we take the combined smoothed dataset into long format so that we can plot the data using ggplot() functions.

# Results
## Plot Data
The following script plots the smoothed dataset and formats it to look as close as I could get it to figure 4 of the Schaefer paper. It uses several ggplot() parameters and functions to achieve the desired look. A .png form of the final figure is outputted at he end of this code; it can be found in the /figs folder.

```{r}
#| warning: false
library(tidyverse)
lter_smoothed_output <- read_csv("../output/lter_smoothed_output.csv")

ggplot(
  data = lter_smoothed_output,
  mapping = aes(
    x = window_start,
    y = window_mean,
    group = sample_id,
    linetype = sample_id
  )
) +
  geom_line() +
  geom_vline(xintercept = ymd("1989-09-18"), linetype = "dashed") +
  theme_linedraw() +
  theme(legend.position = c(.97, .91)) +
  facet_grid(rows = vars(ions), scales = "free_y", switch = "y") +
  ylab("Ions") +
  xlab("Years") +
  labs(title = "Hurricane Effects on Stream Chemistry", linetype = "")

ggsave("../figs/fig3_recreation.png")
```